---
title: "Cluster annotation"
author: "Max J Karlsson & María Bueno Alvez"
date: "23/07/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Run Checklist

## 1. Make sure the dataset metadata is the correct file

## 2. Check that gene dictionaries and databases are the right version

##---
##---

# Setup

## Load libraries
```{r setup, include=FALSE}

library(tidyverse)
library(tidytext)
library(multidplyr)
library(magrittr)
library(rrvgo)
library(treemapify)
library(pbapply)
library(clusterProfiler)
library(patchwork)
library(ggrastr)
source("scripts/functions_utility.R")
source("scripts/generate_gene_clusters.R")

select <- dplyr::select
slice <- dplyr::slice
rename <- dplyr::rename
simplify <- clusterProfiler::simplify


```

## File structure
```{r}

dataset_metadata <- read_csv("run_settings/20210928_settings.csv")

data_paths <- read_csv("run_settings/20211005 all_datasets.csv")

file_structure <-
  create_folder_structure(dataset_id = dataset_metadata$dataset_id,
                          dataset_run_id = dataset_metadata$version,
                          main_folder = "results/Clustering_results",
                          folders = c("data" = "data", 
                                      "svg" = "svg",
                                      "bubbleheatmap" = "svg/bubble",
                                      "treemap" = "svg/treemap",
                                      "heatmap" = "svg/heatmap",
                                      "enrichment" = "enrichment",
                                      "clustering" = "clustering"))
```


## Load clustering data

```{r}

clustering_data <- 
  file_structure %>% 
  map(function(x) x$clustering) %>% 
  map(function(x) {
    file_ <- paste(x, "final_consensus.tsv", sep = "/")
    if(file.exists(file_)) {
      read_tsv(file_)
    } else {
      NULL
    }
  }) %>% 
  bind_rows(.id = "dataset_id") %>% 
  mutate(cluster = as.character(cluster)) 


```

## Load gene mapping

```{r}
entrez_dict <- 
  read_tsv("data/meta/ensembl103_entrez.txt") %>% 
  select(ensg_id = 1, 
         entrez = 2) %>% 
  filter(!is.na(entrez))

gene_info <- 
  read_tsv("data/meta/geneinfo_103.tsv")

```


## Load databases

```{r}

enrichment_settings <- 
  read_csv("run_settings/20211013_enrichment_settings.csv")


enrichment_settings_versions <- 
  enrichment_settings %>% 
  mutate(version = case_when(is.na(version) & 
                               id == "KEGG" ~ gsub("-", "", Sys.Date()),
                             !is.na(version) ~ version))


GO_formatting_function <- 
  . %>% 
  select(ensg_id = `Gene stable ID`,
         term = `GO term name`,
         term_id = `GO term accession`) %>% 
  filter(!is.na(term)) %>% 
  distinct() %>% 
  filter(ensg_id %in% clustering_data$gene) %>% 
  group_by(term_id, term) %>% 
  filter(n_distinct(ensg_id) >= 8) %>% 
  ungroup()

HPAspecificity_formatting_function <- 
  . %>% 
  select(ensg_id,
         term = enhanced_tissues) %>% 
  mutate(term = gsub(", ", ";", term)) %>% 
  separate_rows(term, sep = ",") %>% 
  mutate(term = gsub(";", ", ", term)) %>% 
  filter(!is.na(term)) %>% 
  mutate(term = trimws(term), 
         term_id = term)

database_formatting_functions <- 
  list(secretome_location = . %>% 
         select(ensg_id = Ensembl,
                term = `Secretome location`) %>% 
         filter(!is.na(term)) %>% 
         mutate(term_id = term),
       
       specificity_blood = HPAspecificity_formatting_function,
       specificity_brain = HPAspecificity_formatting_function,
       specificity_tissue = HPAspecificity_formatting_function,
       specificity_celline = HPAspecificity_formatting_function,
       specificity_singlecell = HPAspecificity_formatting_function,
       
       subcellular_location = . %>% 
         filter(Gene %in% clustering_data$gene) %>% 
         select(ensg_id = Gene, 
                Enhanced, 
                Supported, 
                Approved) %>% 
         gather(reliability, location, -1) %>% 
         filter(!is.na(location)) %>% 
         separate_rows(location, sep = ";") %>% 
         select(ensg_id, term = location) %>% 
         mutate(term_id = term),
       
       panglao_cellmarkers = . %>% 
         filter(grepl("Hs", species), 
                `gene type` %in% c("protein-coding gene",
                                   "protein coding gene")) %>% 
         select(gene_name = 2, 
                term = 3) %>% 
         distinct() %>% 
         mutate(term_id = term),
       
       protein_class = . %>% select(ensg_id = Ensembl,
                                    protein_class = `Protein class`) %>% 
         separate_rows(protein_class, sep = ", ") %>% 
         rename(term = protein_class) %>% 
         mutate(term_id = term),
       
       reactome = . %>% 
         filter(species == "Homo sapiens") %>% 
         select(ensg_id, term = description, term_id = id) %>% 
         distinct() %>% 
         filter(ensg_id %in% clustering_data$gene), 
       
       trrust = . %>% 
         select(gene_name, term) %>% 
         mutate(term_id = term),
       
       GO_BP_original = . %>% 
         filter(`GO domain` == "biological_process") %>% 
         GO_formatting_function,
       GO_MF_original = . %>% 
         filter(`GO domain` == "molecular_function") %>% 
         GO_formatting_function,
       GO_CC_original = . %>% 
         filter(`GO domain` == "cellular_component") %>% 
         GO_formatting_function)



gene_formatting_functions <- 
  list(`gene names` = . %>% 
         left_join(gene_info %>% 
                     select(ensg_id, gene_name),
                   by = c("gene_name")) %>% 
         select(ensg_id, term, term_id))


database_terms <- 
  enrichment_settings %>% 
  filter(!is.na(file)) %>% 
  group_by(id) %>% 
  do({
    g_data <<- .
    
    raw_db <- 
      read_tsv(paste0("annotation_databases/", g_data$file))
    
    db_format_function <- 
      database_formatting_functions[[g_data$id]]
    
    out_db <- 
      raw_db %>% 
      db_format_function()
    
    if(g_data$gene_format != "ensembl") {
      gene_format_function <- gene_formatting_functions[[g_data$gene_format]]
      
      out_db <- 
        out_db %>%
        gene_format_function()
      
    }
    
    stopifnot(all(names(out_db) == c("ensg_id", "term", "term_id")))
    
    out_db
    
  }) %>% 
  ungroup()


database_terms %>%
  filter(id %in% c("GO_BP_original", 
                   "GO_CC_original",
                   "GO_MF_original")) %>% 
  group_by(id, term_id, term) %>% 
  summarise(n = n_distinct(ensg_id))%>% 
  # filter(grepl("GO", id)) %>% 
  mutate(type = case_when(n < 8 ~ as.character(n),
                          T ~ "8+")) %>%
  group_by(id, type) %>% 
  count() %>%  
  ggplot(aes(id, n, label = n, fill = type)) +
  geom_col(color = "black") +
  geom_text(position = position_stack(vjust = 0.5)) +
  facet_wrap(~id, nrow = 1, scales = "free") +
  scale_fill_manual(values = colorRampPalette(c("orangered", "gray"))(8)) +
  theme_bw()


```


#Enrichment analyses

##KEGG

```{r}

worker_cluster <- new_cluster(n = 5)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse"))
cluster_copy(worker_cluster, c("compareCluster"))

clustering_data_entrez <- 
  clustering_data %>%
  left_join(entrez_dict,
            by = c("gene" = "ensg_id")) 

KEGG_enrichment_res <- 
  clustering_data_entrez %>% 
  
  group_by(dataset_id) %>% 
  partition(worker_cluster) %>% 
  do({
    dataset_data <- .
    compareCluster(entrez ~ cluster,
                   fun = "enrichKEGG",
                   data = dataset_data,
                   universe = unique(dataset_data$entrez)) %>% 
      as_tibble()
  }) %>% 
  ungroup() %>% 
  collect()




rm(worker_cluster)

```

## Other databases

```{r}
# worker_cluster <- new_cluster(n = 5)
# cluster_library(worker_cluster, c("dplyr",
#                                   "tidyverse"))
# cluster_copy(worker_cluster, c("compareCluster", 
#                                "simplify", 
#                                "min"))
# 
# 
# dataset_res <- 
#   compareCluster(gene ~ cluster,
#                  fun = "enrichGO",
#                  data = dataset_data,
#                  keyType = "ENSEMBL",
#                  OrgDb = "org.Hs.eg.db",
#                  minGSSize = 10,
#                  maxGSSize = 500,
#                  universe = unique(dataset_data$gene),
#                  ont = ontology) 
# 
# bind_rows(simplified = dataset_res %>% 
#             simplify(cutoff = 0.7, by = "p.adjust", select_fun = min) %>% 
#             as_tibble(),
#           original = dataset_res %>% 
#             as_tibble(),
#           .id = "simplified")

### -------------------
worker_cluster <- new_cluster(n = 5)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse"))
cluster_copy(worker_cluster, c("enricher"))

database_enrichment_res <- 
  database_terms %>% 
  group_by(id) %>% 
  do({
    # For each database
    database <- .
    
    term2gene <- 
      database %>% 
      select(term_id, ensg_id)
    
    cluster_copy(worker_cluster, c("term2gene"))
    
    # For 
    clustering_data %>% 
      group_by(dataset_id) %>% 
      
      do({
        g_clustering_data <- .
        
        g_clustering_data %>% 
          group_by(cluster) %>% 
          partition(worker_cluster) %>%
          do({
            g_data <- .
            
            pull(g_data, gene) %>% 
              enricher(maxGSSize = Inf, 
                       universe = unique(g_clustering_data$gene),
                       TERM2GENE = term2gene) %>% 
              as_tibble()
          }) %>% 
          ungroup() %>% 
          collect()
        
      }) %>% 
      ungroup() 
    
  }) %>% 
  ungroup()

rm(worker_cluster)

```

## Simplify GO

```{r}

# Generate similarity matrix for all significant GO terms:
GO_sim <-
  pblapply(c("BP" = "GO_BP_original",
             "CC" = "GO_CC_original", 
             "MF" = "GO_MF_original"),
           function(ont_) {
             GO_terms <-
               database_enrichment_res %>% 
               filter(id == ont_) %>% 
               pull(ID) %>% 
               unique()
             
             calculateSimMatrix(GO_terms, 
                                orgdb = "org.Hs.eg.db",
                                keytype = "ENSEMBL",
                                ont = str_extract(ont_, "BP|CC|MF"),
                                method = "Wang")
           })


GO_sim_terms <- 
  GO_sim %>% 
  map(. %>% 
        colnames() %>% 
        enframe()) %>% 
  bind_rows() %>% 
  pull(value)

worker_cluster <- new_cluster(n = 6)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse"))
cluster_copy(worker_cluster, c("GO_sim", 
                               "reduceSimMatrix"))


simplified_GO_res <- 
  database_enrichment_res %>%
  filter(id %in% c("GO_BP_original",
                   "GO_CC_original", 
                   "GO_MF_original")) %>% 
  filter(ID %in% GO_sim_terms) %>% 
  mutate(GeneFrac = as.numeric(gsub("\\/.*", "", GeneRatio)) /
           as.numeric(gsub(".*\\/", "", GeneRatio)),
         ontology = str_extract(id, "BP|CC|MF")) %>% 
  group_by(ontology, id, dataset_id, cluster) %>% 
  filter(n_distinct(ID) >= 2) %>% 
  group_by(ontology, id, dataset_id, cluster) %>% 
  partition(worker_cluster) %>%
  do({
    g_data <<- .
    
    g_terms <- 
      g_data$ID[which(g_data$ID %in% colnames(GO_sim[[unique(g_data$ontology)]]))]
    
    sim_mat <- 
      GO_sim[[unique(g_data$ontology)]][g_terms,
                                        g_terms]
    
    sim_mat %>%
      reduceSimMatrix(setNames(-log10(g_data$p.adjust), g_data$ID),
                      threshold=0.7,
                      orgdb="org.Hs.eg.db") %>%
      as_tibble() %>%
      rename(term_cluster = cluster)
    
    
  }) %>% 
  ungroup() %>% 
  collect()

rm(worker_cluster)


database_enrichment_res_simplified_GO <- 
  simplified_GO_res %>% 
  select(any_of(names(database_enrichment_res)), 
         ID = parent) %>% 
  distinct() %>%
  left_join(database_enrichment_res) %>% 
  bind_rows(database_enrichment_res %>%
              filter(id %in% c("GO_BP_original",
                               "GO_CC_original", 
                               "GO_MF_original")) %>% 
              group_by(id, dataset_id, cluster) %>% 
              filter(!(n_distinct(ID) >= 2))) %>% 
  mutate(id = gsub("original", "simplified", id))

```



##Save results

```{r}

###########
all_res <-
  list(KEGG_enrichment_res %>% 
         mutate(test_type = "KEGG") %>% 
         select(-Cluster),
       
       database_enrichment_res %>% 
         rename(test_type = id) %>% 
         
         left_join(database_terms %>% 
                     select(test_type = id, 
                            ID = term_id, 
                            Description2 = term) %>% 
                     distinct()) %>% 
         mutate(Description = ifelse(test_type != "KEGG",
                                     Description2, 
                                     Description)) %>% 
         select(-Description2), 
       
       database_enrichment_res_simplified_GO %>% 
         rename(test_type = id) %>% 
         
         left_join(database_terms %>% 
                     select(ID = term_id, 
                            Description2 = term) %>% 
                     distinct()) %>% 
         mutate(Description = ifelse(test_type != "KEGG",
                                     Description2, 
                                     Description)) %>% 
         select(-Description2)) %>% 
  bind_rows() %>% 
  mutate(GeneFrac = as.numeric(gsub("\\/.*", "", GeneRatio)) /
           as.numeric(gsub(".*\\/", "", GeneRatio)),
         BgFrac = as.numeric(gsub("\\/.*", "", BgRatio)) /
           as.numeric(gsub(".*\\/", "", BgRatio)),
         odds_ratio = GeneFrac / BgFrac)   %>% 
  left_join(enrichment_settings_versions %>% 
              select(test_type = id,
                     test_description = description, 
                     database_version = version)) %>% 
  
  select(dataset_id, test_type, test_description, database_version, 
         cluster, ID, Description,
         GeneRatio, GeneFrac, BgRatio, BgFrac, odds_ratio, everything()) 


all_res %>% 
  group_by(dataset_id) %>% 
  do({
    g_data <<- .
    
    enrichment_savefile <- 
      paste(file_structure[[unique(g_data$dataset_id)]]$enrichment,
            "enrichment_results.tsv",
            sep = "/")
    
    write_tsv(g_data,
              enrichment_savefile)
    
  })






```

# Generate plots

## Treemaps

```{r}

ontology_pal <- 
  c("MF" = "#FF6F00",
    "CC" = "#C71B00",
    "BP" = "#018EA0")



# Generate plot legend: 


plot_legend <-
  enframe(ontology_pal,
          "Ontology", 
          "Color") %>% 
  ggplot(aes(1, 1, fill = Ontology)) +
  geom_tile() +
  scale_fill_manual(values = ontology_pal)
plot_legend <- 
  ggpubr::get_legend(plot_legend) %>% 
  ggpubr::as_ggplot()

file_structure %>% 
  map(function(x) x$treemap) %>% 
  lapply(function(treemap_path) {
    ggsave(paste(treemap_path, "treemap_legend.svg",
                 sep = "/"),
           plot = plot_legend,
           width = 1, height = 1)
  })

# Generate plot data for treemaps

# plot_data %>% 
#   group_by(dataset_id, cluster) %>% 
#   do({
#     g_data <- .
#     
#     treemap_savefile <- 
#       paste0(file_structure[[unique(g_data$dataset_id)]]$treemap,
#              "/",
#              "treemap_", 
#              unique(g_data$cluster),
#              ".svg")
#     
#     
#     
#   })


plot_settings <-
  simplified_GO_res %>% 
  select(dataset_id, cluster) %>% 
  mutate(cluster = as.numeric(cluster)) %>% 
  arrange(dataset_id, cluster) %>% 
  distinct() %>% 
  ungroup() %>% 
  mutate(i = row_number(), 
         treemap_folder = file_structure[dataset_id] %>% 
           map(function(x) x$treemap) %>% 
           unlist(),
         treemap_savefile = paste0(treemap_folder,
                                   "/",
                                   "treemap_", 
                                   cluster,
                                   ".svg"))

plots <- 
  pblapply(plot_settings$i,
           function(i) {
             simplified_GO_res %>% 
               filter(dataset_id == plot_settings$dataset_id[i],
                      cluster == plot_settings$cluster[i]) %>% 
               left_join(enframe(ontology_pal,
                                 "ontology", 
                                 "color"),
                         by = "ontology") %>% 
               group_by(parent) %>% 
               mutate(nn = n_distinct(go),
                      color2 = spread_colors(unique(color), n_distinct(go), colorrange = 0.2)) %>% 
               ggplot(aes(area = score, subgroup = parentTerm)) +
               
               geom_treemap(aes(fill = color2), 
                            color = "black",
                            show.legend = T) +
               geom_treemap_subgroup_border(color = "black") +
               
               geom_treemap_text(aes(label = term),
                                 colour = "black", 
                                 place = "centre",
                                 alpha = 0.4,
                                 grow = TRUE) +
               
               geom_treemap_subgroup_text(place = "centre", 
                                          grow = T, 
                                          reflow = T,
                                          alpha = 1, 
                                          colour = "white", 
                                          fontface = "bold",
                                          min.size = 0) +
               
               scale_fill_identity() +
               theme_void() 
             
           })


for(i in plot_settings$i) {
  setting <- 
    plot_settings[i, ]
  ggsave(setting$treemap_savefile,
         plots[[i]],
         width = 6, height = 4)
}

```

## Heatmaps

```{r}
# cluster_membconf_data <- 
#   clustering_data %>% 
#   # filter(dataset_id == "tissue") %>% 
#   select(dataset_id, ensg_id = gene, cluster) %>% 
#   mutate(cluster_membership_confidence = rnorm(nrow(.), 0.95, 0.05),
#          cluster_membership_confidence = ifelse(cluster_membership_confidence > 1, 
#                                                 1, 
#                                                 round(cluster_membership_confidence, 2)))
# 


cluster_membconf_data <-
  clustering_data %>% 
  group_by(dataset_id) %>% 
  do({
    g_data <- .
    g_dataset_id <- unique(g_data$dataset_id)
    
    membership_file <- 
      paste(file_structure[[g_dataset_id]]$clustering, "cluster_memberships.tsv", sep = "/")
    
    read_tsv(membership_file) %>% 
      as_tibble() %>% 
      rename(cluster_membership_confidence =  membership,
             ensg_id = gene) 
  })

heatmap_palette <- 
  colorRampPalette(c("white", "orangered"))(100)

heatmap_data <-
  readRDS("data/processed/combined_HPA_expression_data.RDS")

heatmap_settings <- 
  dataset_metadata %>%
  select(dataset_id, heatmap = type, additional_heatmap) %>% 
  gather(heatmap_type, type, heatmap, additional_heatmap) %>% 
  filter(!is.na(type)) %>% 
  left_join(data_paths) %>%
  filter(!is.na(filename)) %>% 
  left_join(clustering_data %>% 
              select(dataset_id, cluster) %>% 
              distinct())

heatmap_data_scaled <- 
  heatmap_data %>%
  map(. %>% 
        gather(sample, value, -1) %>% 
        group_by(ensg_id) %>% 
        mutate(value_scaled = value / max(value),
               value_zscore = (value - mean(value, na.rm = T)) / 
                 sd(value, na.rm = T)) %>% 
        ungroup()) %>% 
  bind_rows(.id = "id") %>% 
  separate(id, into = c("dataset_id", "type")) %>% 
  inner_join(clustering_data %>% 
               select(dataset_id, gene, cluster),
             by = c("dataset_id",
                    "ensg_id" = "gene")) %>% 
  left_join(heatmap_settings)


worker_cluster <- new_cluster(n = 5)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse"))
cluster_copy(worker_cluster, c("file_structure",
                               "cluster_membconf_data"))





heatmap_data_scaled %>% 
  group_by(dataset_id, heatmap_type, cluster) %>%  
  # partition(worker_cluster) %>%
  do({
    g_cluster_data <<- .
    
    g_dataset_id <- unique(g_cluster_data$dataset_id)
    
    g_heatmap_type <- unique(g_cluster_data$heatmap_type)
    
    
    plot_savename_zscore <- 
      paste0(file_structure[[g_dataset_id]]$heatmap, "/",
             g_heatmap_type,
             "_zscore_",
             unique(g_cluster_data$cluster), 
             ".svg")
    
    plot_savename_scaled <- 
      paste0(file_structure[[g_dataset_id]]$heatmap, "/",
             g_heatmap_type,
             "_scaled_",
             unique(g_cluster_data$cluster), 
             ".svg")
    
    
    g_cluster_data_wide <- 
      g_cluster_data %>% 
      select(ensg_id, sample, value_zscore) %>% 
      spread(sample, value_zscore) %>% 
      column_to_rownames("ensg_id") 
    
    gene_hclust <- 
      g_cluster_data_wide %>% 
      dist() %>% 
      hclust(method = "ward.D2")
    
    sample_hclust <- 
      g_cluster_data_wide %>%
      t() %>% 
      dist() %>% 
      hclust(method = "ward.D2")
    
    plot_data <- 
      g_cluster_data %>% 
      mutate(ensg_id = factor(ensg_id, 
                              rev(gene_hclust$labels[gene_hclust$order])),
             sample = factor(sample, 
                             sample_hclust$labels[sample_hclust$order])) 
    
    plot_confidence <- 
      cluster_membconf_data %>%
      filter(dataset_id == g_dataset_id) %>% 
      filter(ensg_id %in% gene_hclust$labels) %>% 
      filter(cluster == unique(g_cluster_data$cluster)) %>% #-> addition to filter memberships for other clusters
      mutate(ensg_id = factor(ensg_id, 
                              rev(gene_hclust$labels[gene_hclust$order]))) %>% 
      ggplot(aes("Confidence", ensg_id, fill = cluster_membership_confidence)) + 
      geom_tile_rast() +
      theme_void() +
      scale_fill_gradient(low = "#D1EEEA", high = "#2A5674",
                          limits = c(0.2, 1), # before limit to 0.5
                          breaks = c(0.5, 0.75, 1),
                          name = "Confidence") +
      theme(axis.text.x = element_text(angle = -90, face = "bold"), 
            legend.position = "left")
    
    plot_heat_zscore <- 
      plot_data %>% 
      ggplot(aes(sample, ensg_id, fill = value_zscore)) +
      geom_tile_rast() +
      scale_fill_gradient2(low = "#4575B4", high = "#D73027", mid = "#FFFFFF",
                           name = "Z-score") +
      theme_void() +
      theme(axis.text.x = element_text(angle = -90,
                                       hjust = 0, 
                                       size = 6),
            legend.position = "top")
    
    
    plot_heat_scaled <- 
      plot_data %>% 
      ggplot(aes(sample, ensg_id, fill = value_scaled)) +
      geom_tile_rast() +
      scale_fill_gradient2(low = "#4575B4", high = "#D73027", mid = "#FFFFFF",
                           name = "Relative Expression",
                           breaks = c(0, 0.5, 1),
                           limits = c(0, 1)) +
      theme_void() +
      theme(axis.text.x = element_text(angle = -90,
                                       hjust = 0,
                                       size = 6),
            legend.position = "top")
    
    column_width <- (1/53)
    plot_n <- length(sample_hclust$labels)
    plot_scaling_factor <- column_width * plot_n
    
    plot_widths <- 
      c(3, plot_n) %>% 
      {. * column_width} %>% 
      {. / max(.)}
    
    plot_width <- 
      1 + 4 * plot_scaling_factor
    
    p1 <- 
      plot_confidence + plot_heat_zscore +
      plot_layout(widths = plot_widths, nrow = 1)
    p2 <- 
      plot_confidence + plot_heat_scaled +
      plot_layout(widths = plot_widths, nrow = 1)
    
    ggsave(plot_savename_zscore, plot = p1,  
           width = plot_width, 
           height = 5)
    ggsave(plot_savename_scaled, plot = p2,
           width = plot_width, 
           height = 5)
    
    tibble()
  }) %>% 
  ungroup() %>% 
  collect()

rm(worker_cluster)

```

## Bubble heatmaps


```{r}

bubble_heatmap_settings <- 
  all_res %>%
  filter(!test_type %in% c("KEGG",
                           "GO_BP_original",
                           "GO_CC_original",
                           "GO_MF_original",
                           "GO_BP_simplified",
                           "GO_CC_simplified",
                           "GO_MF_simplified",
                           "reactome")) %>% 
  group_by(dataset_id, test_type) %>% 
  summarise(bubbles = length(ID),
            clusters = n_distinct(cluster),
            terms = n_distinct(Description)) %>% 
  ungroup() %>% 
  mutate(i = row_number(), 
         bubble_folder = file_structure[dataset_id] %>% 
           map(function(x) x$bubbleheatmap) %>% 
           unlist(),
         bubble_savefile = paste0(bubble_folder,
                                  "/",
                                  "bubble_", 
                                  test_type,
                                  ".svg"))

plot_data_all <- 
  all_res %>% 
  group_by_all() %>% 
  mutate(capped_odds_ratio = min(c(odds_ratio,
                                   50))) %>% 
  ungroup()

cluster_levels <- 
  clustering_data %>% 
  select(dataset_id, cluster) %>% 
  distinct() %>% 
  arrange(dataset_id, as.numeric(cluster)) 


plot_size_range <- c(1, 4)

plot_legend_settings <- 
  tibble(odds_ratio_str = c(1, 10, 20, 30, 40, ">50"),
         y = 1:6,
         odds_ratio = c(1, 10, 20, 30, 40, 50)) 

plot_legend <-
  plot_legend_settings %>% 
  ggplot(aes(1, y, 
             size = odds_ratio,
             fill = odds_ratio,
             label = odds_ratio_str)) +
  geom_point(shape = 21,
             show.legend = F) +
  geom_text(size = 4, 
            hjust = 0,
            nudge_x = 0.1) +
  annotate("text", x = 1, y = 7, label = "Odds ratio",
           fontface = "bold", hjust = 0) +
  scale_x_continuous(limits = c(0, 2)) +
  scale_y_continuous(limits = c(0, 7)) +
  scale_fill_gradient(name = "Odds ratio",
                      low = "white", high = "orangered",
                      breaks = plot_legend_settings$odds_ratio,
                      limits = range(plot_legend_settings$odds_ratio)) + 
  scale_size_continuous(name = "Odds ratio", 
                        range = plot_size_range, 
                        breaks = plot_legend_settings$odds_ratio,
                        limits = range(plot_legend_settings$odds_ratio)) +
  theme_void()

for(folder_ in unique(bubble_heatmap_settings$bubble_folder)) {
  ggsave(paste0(folder_, "/legend.svg"),
         plot = plot_legend,
         width = 2, 
         height = 2)
} 

plots <- 
  pblapply(1:nrow(bubble_heatmap_settings), 
           function(i) {
             i <<- i
             dataset_id_ <- 
               bubble_heatmap_settings$dataset_id[i]
             test_type_ <- 
               bubble_heatmap_settings$test_type[i]
             filename <- 
               bubble_heatmap_settings$bubble_savefile[i]
             
             plot_data <- 
               plot_data_all %>% 
               filter(dataset_id == dataset_id_,
                      test_type == test_type_) %>% 
               mutate(cluster = paste0("cluster_", cluster, "_"))
             
             plot_levels <-
               cluster_levels %>% 
               mutate(cluster = paste0("cluster_", cluster, "_")) %>% 
               filter(dataset_id == dataset_id_) %>% 
               pull(cluster)
             
             plot_clustering <- 
               plot_data %>% 
               select(cluster, ID, odds_ratio) %>% 
               spread(ID, odds_ratio, fill = 0) %>% 
               column_to_rownames("cluster") %>%
               list(tissue = t(.), 
                    cluster = .) %>%
               map(. %>% 
                     dist(method = "binary") %>% 
                     hclust(method = "ward.D2"))
             
             plot_order <- 
               list(cluster = unique(c(with(plot_clustering$cluster,
                                            labels[order]),
                                       plot_levels)),
                    ID = with(plot_clustering$tissue,
                              labels[order]))
             
             plot <-
               plot_data %>%
               ungroup() %>% 
               mutate(cluster = factor(cluster,
                                       plot_order$cluster),
                      ID = factor(ID,
                                  plot_order$ID)) %>%
               ggplot(aes(ID, cluster, 
                          size = capped_odds_ratio, 
                          fill = capped_odds_ratio)) +
               geom_point(data = expand_grid(cluster = plot_order$cluster,
                                             ID = plot_order$ID) %>% 
                            mutate(cluster = factor(cluster, unique(cluster)),
                                   ID = factor(ID, unique(ID))),
                          fill = NA,
                          size = NA) +
               geom_point(shape = 21,
                          show.legend = F) +
               theme_bw() +
               theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.5),
                     legend.position = "right") +
               # coord_fixed() +
               scale_fill_gradient(name = "Odds ratio",
                                   low = "white", high = "orangered",
                                   breaks = plot_legend_settings$odds_ratio,
                                   limits = range(plot_legend_settings$odds_ratio)) + 
               scale_size_continuous(name = "Odds ratio", 
                                     range = plot_size_range, 
                                     breaks = plot_legend_settings$odds_ratio,
                                     limits = range(plot_legend_settings$odds_ratio)) +
               theme(axis.title = element_blank(), 
                     plot.margin = unit(c(0,0,0,200), "pt")) + 
               coord_fixed()
             
             column_width <- (1/30)#(1/53)
             plot_n <- length(plot_order$ID)
             plot_scaling_factor_row <- column_width * plot_n
             
             plot_n_col <- length(plot_order$cluster)
             plot_scaling_factor_col <- column_width * plot_n_col
             
             # 
             # plot_widths <- 
             #   c(3, length(plot_n)) %>% 
             #   {. * column_width} %>% 
             #   {. / max(.)}
             
             plot_width <- 
               4 + 4 * plot_scaling_factor_row
             plot_height <- 
               2 + 4 * plot_scaling_factor_col
             
             ggsave(filename,
                    plot = plot,
                    width = plot_width, height = plot_height)
             
           })



```


