---
title: "HPA gene clustering"
author: "Max J Karlsson & María Bueno Alvez"
date: "08/06/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Setup
```{r setup, include=FALSE}
library(vroom)
library(tidyverse)
library(magrittr)
library(pbapply)
library(uwot)
library(igraph)
library(edgebundle)
library(viridis)
library(pcaMethods)
library(factoextra)
library(Seurat)
library(uwot)
library(plotly)
library(htmlwidgets)
library(aricode)
library(clValid)
library(infotheo)
library(ggheatmap)
library(multidplyr)
library(clue)
library(ggalluvial)
library(colorspace)

source("scripts/functions_preprocessing.R")
source("scripts/functions_dimensionalityreduction.R")
source("scripts/functions_clustering.R")
source("scripts/functions_evaluation.R")
source("scripts/cluster rasterizer.R")
source("scripts/generate_gene_clusters.R")
source("scripts/functions_utility.R")
source("scripts/functions_classification.R")

```



## Read metadata
```{r}

dataset_metadata <- read_csv("run_settings/20210928_settings.csv")

```

## Read data
```{r}
all_data <-
  readRDS("data/processed/combined_HPA_expression_data.RDS")

all_data <-
  lapply(1:nrow(dataset_metadata),
         function(i) {
           id_ <- paste(dataset_metadata$dataset_id[i],
                        dataset_metadata$type[i],
                        sep = "_")
           all_data[[id_]]
         }) %>%
  set_names(dataset_metadata$dataset_id)

all_data <- all_data[!sapply(all_data,is.null)] 
  
all_genes_in_data <-
  all_data %>% 
  map(. %>% 
        select(1)) %>% 
  bind_rows() %>% 
  distinct() %>% 
  pull(ensg_id)
```


## Read database data

```{r}

# GO annotation
GOterms <- 
  vroom("data/meta/Ensembl103 GO terms.txt") %>% 
  select(ensg_id = 1, 
         gene_name = 2, 
         GO_accession = 3, 
         GO_domain = 4, 
         GO_term_name = 5, 
         GO_term_evidence = 6) %>% 
  filter(ensg_id %in% all_genes_in_data)

# Other databases
db_terms <- read_tsv("data/database_terms.tsv")
  
```

## Settings

```{r}

run_settings <- 
  list(num_seeds = 100,
       final_consensus_resolutions = 
         list("blood" = 4.7,
              "brain" = 6.1,
              "celline" = 1.7,
              "singlecell" = 3.1,
              "tissue" = 7.3),
       resolution_upper_limit = c("blood" = 14.5,
                            "brain" = 12.5,
                            "celline" = 15,
                            "singlecell" = 20,
                            "tissue" = 11.1),
       resolution_lower_limit = c("blood" = 0.5,
                            "brain" = 0.5,
                            "celline" = 0.3,
                            "singlecell" = 0.5,
                            "tissue" = 0.5),
       n_neighbors = c("blood" = 20,
                            "brain" = 20,
                            "celline" = 20,
                            "singlecell" = 20,
                            "tissue" = 20),
       pruning = c("blood" = 1/15,
                            "brain" = 1/15,
                            "celline" = 1/15,
                            "singlecell" = 1/20,
                            "tissue" = 1/15))

#saveRDS(run_settings, ".rds")

```


## Color data 

```{r}

dataset_palette <- c("tissue" = "#0083C4",  "brain" = "#FFDD00", "blood" = "#CF161A","singlecell" = "#6AA692", "celline" = "#97CF16")
reliability_palette <- c("High" = "#122740", "Medium" = "#568F8B", "Low" = "#F4F6CC") 
```

## File structure
```{r}

file_structure <-
  create_folder_structure(dataset_id = dataset_metadata$dataset_id,
                          dataset_run_id = dataset_metadata$version,
                          main_folder = "results/Clustering_results", 
                          folders = c("svg" = "svg",
                                      "data" = "data",
                                      "treemap" = "svg/treemap",
                                      "heatmap" = "svg/heatmap",
                                      "PCA" = "PCA",
                                      "distance" = "distance",
                                      "graph" = "graph",
                                      "UMAP" = "UMAP",
                                      "enrichment" = "enrichment",
                                      "clustering" = "clustering",
                                      "evaluation" = "evaluation"))

saveRDS(file_structure, "run_settings/file_structure.rds")
```


# Clustering
## Screening clustering
```{r}

# Define which genes are expressed per dataset
gene_max_exp <- 
  all_data %>% 
  map(. %>%
        column_to_rownames("ensg_id") %>% 
        apply(MARGIN = 1,
              max) %>% 
        enframe("ensg_id", "max_exp")) %>% 
  bind_rows(.id = "dataset_id")

expressed_genes <- 
  gene_max_exp %>% 
  filter(max_exp >= 1) %>% 
  select(1, 2)

# Prepare cluster for parallelization
cluster <- new_cluster(n = 6)
cluster_library(cluster, c("dplyr",
                           "tidyverse",
                           "factoextra",
                           "pcaMethods",
                           "Seurat",
                           "magrittr",
                           "cluster",
                           "clValid",
                           "vroom")) 
cluster_copy(cluster, c("HPA_gene_clustering", 
                        "generate_savefile", 
                        "scale_data",
                        "calculate_pca",
                        "calculate_distance",
                        "cluster_genes", 
                        "file_structure",
                        "run_settings"))

# Generate clusterings
t <- Sys.time()
all_data_cluster <- 
  all_data %>% 
  map(. %>% 
        gather(sample_id, tmm, -1)) %>% 
  bind_rows(.id = "dataset_id") %>% 
  inner_join(expressed_genes) %>% 
  group_by(dataset_id) %>%    
   partition(cluster) %>% 
  do({
    g_data <- .

    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_cluster <- 
      paste(file_structure[[g_dataset_id]]$clustering, "screening_clustering.tsv", sep = "/")
    
    if(file.exists(savefile_cluster)) {
      cluster_res <-
        read_tsv(savefile_cluster)  
        
    } else {
      savefile_pca = paste(file_structure[[g_dataset_id]]$PCA, "PCA.rds", sep = "/")
      savefile_pca_plot = paste(file_structure[[g_dataset_id]]$PCA, "PCA_plot.pdf", sep = "/")
      savefile_dist = paste(file_structure[[g_dataset_id]]$distance, "distances.rds", sep = "/")
      savefile_neighbors = paste(file_structure[[g_dataset_id]]$graph, "neighbors.rds", sep = "/")
      savefile_data = paste(file_structure[[g_dataset_id]]$data, "data.tsv", sep = "/")
      
      write_tsv(g_data, savefile_data)
      
      cluster_res <-
        HPA_gene_clustering(g_data,
                            col_value = "tmm",
                            col_gene = "ensg_id",
                            col_sample = "sample_id",
                            savefile_pca = savefile_pca,
                            savefile_pca_plot = savefile_pca_plot,
                            savefile_dist = savefile_dist,
                            savefile_neighbors = savefile_neighbors,
                            scaling = "zscore",
                            distance_metric = "spearman",
                            clustering_method = "louvain",
                            seed = 1:run_settings$num_seeds,
                            resolution = seq.int(run_settings$resolution_lower_limit[[g_dataset_id]],
                                                 run_settings$resolution_upper_limit[[g_dataset_id]], by = 0.2), 
                            npcs = 100,
                            log_transform = F,
                            n_neighbors = run_settings$n_neighbors[[g_dataset_id]],
                            pruning = run_settings$pruning[[g_dataset_id]])  
      
      cluster_res <- 
        cluster_res$cluster_data %>% 
        mutate(cluster = as.character(cluster + 1))%>%
        group_by(resolution, seed) %>%
        mutate(k = n_distinct(cluster)) %>%
        ungroup() %>%
        group_by(resolution) %>%
        mutate(resolution_k = ceiling(median(k))) %>%
        ungroup() %>%
        filter(resolution_k >= 30,
               resolution_k <= 110) %>%
        select(-k, -resolution_k) %>%
        spread(seed, cluster, sep = "_")
      
      write_tsv(cluster_res, savefile_cluster)
    }
    
    cluster_res
    
  }) %>%
  collect() %>% 
  ungroup()

rm(cluster)
Sys.time() - t

all_data_cluster %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(k = n_distinct(seed_1)) %>% 
  ggplot(aes(x = resolution, y = k, color = dataset_id)) +
  geom_point() +
  geom_smooth() +
  theme_bw() +
  facet_grid(~dataset_id) +
  scale_color_manual(values = dataset_palette)


```


## Consensus clustering 
```{r}

# Prepare cluster for parallelization    
cluster <- new_cluster(n = 6)
cluster_library(cluster, c("dplyr",
                           "tidyverse",
                           "magrittr",
                           "clue")) 
cluster_copy(cluster, c("find_consensus", 
                        "to_cluster",
                        "file_structure",
                        "run_settings"))

# Find consensus clustering for each resolution
t <- Sys.time()

all_clusters_consensus <- 
  all_data_cluster %>% 
  group_by(dataset_id) %>% 
  partition(cluster) %>% 
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_cluster <- 
      paste(file_structure[[g_dataset_id]]$clustering, "screening_consensus.tsv", sep = "/")

    
    if(file.exists(savefile_cluster)) {
      consensus <-
        read_tsv(savefile_cluster)
      
    } else {
      
      consensus <- 
        g_data %>% 
        group_by(resolution) %>% 
       # partition(cluster) %>% 
        do({
          dat <- .
          res <- unique(dat$resolution)
          
          final_clustering <- find_consensus(dat, n = run_settings$num_seeds, get_membership = F, runs = 1)
          
       #   savefile_cluster_res <- paste(file_structure[[g_dataset_id]]$clustering, paste(res, "resolution_consensus.tsv", sep = "_"), sep = "/")
        #  write_tsv(final_clustering, savefile_cluster_res)
          
          final_clustering
        }) %>% 
       # collect() %>% 
        ungroup()
      
      write_tsv(consensus, savefile_cluster)
      
      consensus
    }
    
  }) %>%  
   collect() %>% 
  ungroup()

rm(cluster)
Sys.time() - t


all_clusters_consensus %>%
  group_by(dataset_id, resolution) %>%
  summarise(k = n_distinct(cluster)) %>%
  ggplot(aes(x = resolution, y = k, color = dataset_id)) +
  geom_point() +
  geom_smooth() +
  theme_bw() +
  facet_grid(~dataset_id, scales = "free_x") +
  scale_color_manual(values = dataset_palette) +
  xlab("Resolution parameter") +
  ylab("Number of clusters (k)")+ 
  theme(panel.spacing = unit(4, "lines"))

all_clusters_consensus %>%
  group_by(dataset_id) %>%
  summarise(s = n_distinct(resolution))

all_clusters_consensus %>% 
  select(dataset_id, resolution) %>% 
  distinct() %>% 
  mutate(resolution = as.factor(resolution)) %>% 
  mutate(value = 100) %>% 
  ggplot(aes(x = resolution, y = value, fill = dataset_id)) +
  geom_bar(stat = "identity") +
  facet_grid(~dataset_id, scales = "free_x") +
  theme_bw() +
  scale_fill_manual(values = dataset_palette) +
  xlab("Resolution parameter") +
  ylab("Number of runs")
  


```



# Nearest neighbors

```{r}
neighbor_data <-
  file_structure %>%
  map(function(x) x$distance) %>%
  map(function(x) {
    
    nn_file <- paste(x, "nearest_neighbors.tsv", sep = "/")
    
    if(file.exists(nn_file)) {
      nn_data <- read_tsv(nn_file)
    } else {
      file_ <- paste(x, "distances.rds", sep = "/")
      if(file.exists(file_)) {
        distances <-
          readRDS(file_) %>%
          as.matrix()
        nn_data <-
          colnames(distances) %>%
          enframe("i", "gene") %>%
          select(gene) %>%
          group_by(gene) %>%
          do({
            g_gene <- .$gene
            distances[g_gene, ] %>%
              enframe("neighbor_gene", "cor_distance") %>%
              arrange(cor_distance) %>%
              head(20) %>% 
              mutate(cor = 1-cor_distance)
          }) %>%
          ungroup()
        rm(distances)
        write_tsv(nn_data, nn_file)
        nn_data
      } else {
        NULL
      }
    }
  }) %>%
  bind_rows(.id = "dataset_id")


```



# UMAP
## Read graphs
```{r}

all_data_graphs <- 
  file_structure %>% 
  map(function(x)x$graph) %>% 
  lapply(function(filename_) readRDS(paste(filename_, "neighbors.rds", sep = "/")))

```
## Generate UMAP
```{r}
# Generate UMAP from graph 
graph_umaps <- 
  names(all_data_graphs) %>% 
  set_names(., .) %>% 
  pblapply(function(dataset_id_) {
    
    graph_ <- all_data_graphs[[dataset_id_]]
    
    savefile_UMAP <- 
      paste(file_structure[[dataset_id_]]$UMAP, "UMAP.tsv", sep = "/")
    
    if(file.exists(savefile_UMAP)) {
      UMAP_res <-
        read_tsv(savefile_UMAP)
      
    } else {
      
      set.seed(42)

      UMAP_res <- 
        graph_$snn %>% 
        RunUMAP(umap.method = "umap-learn") %>% 
        {.@cell.embeddings} %>% 
        as_tibble(rownames = "gene") 
      
      
      UMAP_res_scaled <- 
        UMAP_res %>% 
        gather(UMAP, UMAP_value, UMAP_1, UMAP_2) %>% 
        mutate(UMAP_value = scales::rescale(UMAP_value, c(-1, 1))) %>% 
        group_by(UMAP) %>% 
        mutate(UMAP_value = UMAP_value - mean(range(UMAP_value))) %>% 
        ungroup() %>%
        spread(UMAP, UMAP_value)  
      
      UMAP_res <- 
        UMAP_res %>% 
        left_join(UMAP_res_scaled,
                  by = "gene", 
                  suffix = c("", "_scaled"))
      
      
      write_tsv(UMAP_res, savefile_UMAP)
    }
    
    
  }) %>% 
  bind_rows(.id = "dataset_id")


graph_umaps %>%
  ggplot(aes(x= UMAP_1_scaled, y =UMAP_2_scaled)) +
  geom_point(size = 0.1) +
  coord_fixed() +
  facet_grid(~dataset_id) +
  theme_bw()

```



# Evaluation
## ARI
```{r Retrieve partitions for ARI}

# Prepare cluster for parallelization
cluster <- new_cluster(n = 5)
cluster_library(cluster, c("dplyr",
                           "tidyverse",
                           "magrittr",
                           "aricode")) 
cluster_copy(cluster, c("file_structure","run_settings")) 


# Calculate ARI index
t <- Sys.time()
ARI_res <- 
  all_data_cluster %>% 
  group_by(dataset_id) %>% 
  partition(cluster) %>% 
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_ARI <- 
      paste(file_structure[[g_dataset_id]]$evaluation, "ARI.tsv", sep = "/")
    
    if(file.exists(savefile_ARI)) {
      ARI_scores <-
        read_tsv(savefile_ARI)
        
    } else {
      
      ARI_scores <- 
        g_data %>% 
        group_by(resolution) %>% 
        do({
          dat <- .
          combn(1:run_settings$num_seeds, m=2) %>% 
            t() %>% 
            as_tibble() %>% 
            set_names(c("seed1", "seed2")) %>% 
            group_by_all() %>% 
            mutate(ARI = ARI(dat %>% select(gene, paste("seed",seed1,sep = "_")) %>%  deframe(), 
                             dat %>% select(gene, paste("seed",seed2,sep = "_")) %>%  deframe()))
          # dat %>%  filter(seed == seed2) %>% select(gene,cluster) %>%  deframe()
          
        }) %>% 
        ungroup()
      
      write_tsv(ARI_scores, savefile_ARI)
    }
    
    ARI_scores
  }) %>% 
    collect() %>% 
    ungroup()

t-Sys.time()


```


## MI
```{r Evaluation based on Mutual Information - Gene Ontology}

# Filter GO database
MI_GOterms <- 
  GOterms %>%
  filter(!is.na(GO_accession),
         !is.na(GO_domain)) %>%
  distinct() %>% 
  group_by(GO_accession) %>% 
  mutate(n_genes = n_distinct(ensg_id)) %>% 
  ungroup() %>% 
  filter(n_genes <= 500, 
          n_genes >= 10) %>% 
  select(ensg_id,GO_accession,GO_domain)

# Prepare cluster for paralellization
worker_cluster <- new_cluster(n = 6)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse",
                                  "infotheo"))
cluster_copy(worker_cluster, c("MI_GOterms",
                               "calculate_MI",
                               "file_structure"))


# Calculate mutual information (GO database)
t <- Sys.time()
MI_res_consensus <-
  all_clusters_consensus %>%
  group_by(dataset_id) %>%
  partition(worker_cluster) %>%
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_MIGO <- 
      paste(file_structure[[g_dataset_id]]$evaluation, "MI_GO.tsv", sep = "/")
    
    if(file.exists(savefile_MIGO)) {
      MI_scores <-
        read_tsv(savefile_MIGO)
        
    } else {
      
      MI_scores <- 
        g_data %>% 
        group_by(resolution) %>% 
        
        do({
          g_data <- .
          select(g_data, gene, cluster) %>%
            calculate_MI(., MI_GOterms, nrep = 500)
        }) %>% 
        ungroup()
      
      write_tsv(MI_scores, savefile_MIGO)
    }
    
    MI_scores
  }) %>%
  ungroup() %>%
  collect()
rm(worker_cluster)
gc()

Sys.time() - t


```

```{r Evaluation based on Mutual Information - Reactome}
# Filter reactome database
MI_Rterms <- 
  db_terms %>%
  filter(id == "reactome") %>% 
  filter(!is.na(term_id)) %>%
  distinct() %>% 
  group_by(term_id) %>% 
  mutate(n_genes = n_distinct(ensg_id)) %>% 
  ungroup() %>% 
  filter(n_genes <= 500, 
          n_genes >= 10) %>% 
  select(ensg_id,term_id)

# Prepare cluster for paralellization
t <- Sys.time()
worker_cluster <- new_cluster(n = 6)
cluster_library(worker_cluster, c("dplyr",
                                  "tidyverse",
                                  "infotheo"))
cluster_copy(worker_cluster, c("MI_Rterms",
                               "calculate_MI_reactome",
                               "file_structure"))

# Calculate mutual information (rectome database)
MI_R_consensus <-
  all_clusters_consensus %>%
  group_by(dataset_id) %>%
  partition(worker_cluster) %>%
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_MIreactome <- 
      paste(file_structure[[g_dataset_id]]$evaluation, "MI_reactome.tsv", sep = "/")
    
    if(file.exists(savefile_MIreactome)) {
      MI_scores <-
        read_tsv(savefile_MIreactome)
        
    } else {
      
      MI_scores <- 
        g_data %>% 
        group_by(resolution) %>% 
        
        do({
          g_data <- .
          select(g_data, gene, cluster) %>%
            calculate_MI_reactome(., MI_Rterms, nrep = 300)
        }) %>% 
        ungroup()
      
      write_tsv(MI_scores, savefile_MIreactome)
    }
    
    MI_scores
  }) %>%
  ungroup() %>%
  collect()
rm(worker_cluster)
gc()

Sys.time() - t

```


## UMAP - cluster dispersion
```{r}
# Prepare cluster for paralellization
cluster <- new_cluster(n = 5)

cluster_library(cluster, c("dplyr",
                           "tidyverse",
                           "magrittr")) 
cluster_copy(cluster, c("file_structure"))

# Calculate UMAP distances
intracluster_distances <- 
  graph_umaps %>% 
  select(-UMAP_1, -UMAP_2) %>% 
  left_join(all_clusters_consensus)%>% 
  group_by(dataset_id) %>% 
  partition(cluster) %>% 
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    intracluster_dist_file <- 
      paste(file_structure[[g_dataset_id]]$evaluation, "intracluster_distances.tsv", sep = "/")
    
    if(file.exists(intracluster_dist_file)) {
      gene_distances <-
        read_tsv(intracluster_dist_file)
      
    } else {
      
      gene_distances <- 
        g_data %>% 
        group_by(resolution) %>% 
        do({
          dat <<- .
          dat %>% 
            group_by(dataset_id,resolution,cluster) %>% 
            do({
              dat <- .
              dat %>% 
                select(gene,UMAP_1_scaled,UMAP_2_scaled) %>%
                column_to_rownames("gene") %>% 
                dist() %>%
                as.matrix() %>% 
                as_tibble(rownames = "gene1") %>% 
                gather(gene2,dist,-1) %>% 
                filter(gene1 < gene2) %>% 
                summarise(dist = mean(dist), 
                          n_genes = n_distinct(dat$gene))
            })
          
          
          
        }) %>% 
        ungroup()
      
      write_tsv(gene_distances, intracluster_dist_file)
    }
    
    gene_distances %>% 
      group_by(dataset_id,resolution) %>% 
      mutate(total_genes = sum(n_genes)) %>% 
      ungroup() %>% 
      mutate(weighted_dist = dist * n_genes / total_genes) %>%  
      group_by(dataset_id, resolution) %>% 
      mutate(avg_weighted_dist = sum(weighted_dist),
             min_size = min(n_genes),
             max_size = max(n_genes),
             avg_size = mean(n_genes)) %>% 
      ungroup()
    
  }) %>% 
  collect() 

rm(cluster)

```
 
## Visualize clustering results
```{r}

resolution_umaps <-
  names(all_data_graphs) %>%
  set_names(., .) %>%
  pblapply(function(dataset_id_) {

    umap <-
      graph_umaps %>%
      select(-UMAP_1, -UMAP_2) %>%
      left_join(all_clusters_consensus) %>%
      filter(dataset_id == dataset_id_)  %>%
      left_join(intracluster_distances %>%
                  as_tibble() %>%
                  filter(dataset_id == dataset_id_) %>%
              select(dataset_id,resolution, cluster,weighted_dist))

    savefile_consensus_UMAP <-
      paste(file_structure[[dataset_id_]]$evaluation, "consensus_clustering_UMAP.pdf", sep = "/")

    if(file.exists(savefile_consensus_UMAP)) {
      break

    } else {

      pdf(savefile_consensus_UMAP)

      plots <-
        lapply(unique(umap$resolution), function(r) {
          umap %>%
            filter(resolution == r) %>%
            arrange(weighted_dist) %>%
            mutate(cluster = factor(cluster, unique(cluster))) %>%
            ggplot(aes(x = UMAP_1_scaled, y = UMAP_2_scaled, color = cluster)) +
            geom_hex(data = graph_umaps %>%
                       filter(dataset_id == dataset_id_),
                     aes(x = UMAP_1_scaled, y = UMAP_2_scaled),
                     fill = "grey",
                     inherit.aes = F,
                     bins = 100) +
            geom_point(size = 0.1, show.legend = F) +
            coord_fixed()+
            facet_wrap(~cluster) +
            theme_void() +
            theme(panel.spacing = unit(0, "mm")) +
            ggtitle(paste(dataset_id_, "dataset: resolution", r))
        })

      plots
      dev.off()
    }
  })



umap <-
  graph_umaps %>%
  filter(dataset_id == "tissue") %>% 
  select(-UMAP_1, -UMAP_2) %>%
  left_join(all_clusters_consensus %>% 
              filter(dataset_id == "tissue",
                     resolution == "7.3") %>% 
              select(-cons_cluster)) 

umap %>%
  ggplot(aes(x = UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_hex(data = graph_umaps %>%
             filter(dataset_id == "tissue"),
           aes(x = UMAP_1_scaled, y = UMAP_2_scaled),
           fill = "grey",
           inherit.aes = F,
           bins = 100) +
  geom_point(size = 0.1, show.legend = F) +
  coord_fixed()+
  facet_wrap(~cluster) +
  theme_void() +
  theme(panel.spacing = unit(0, "mm")) 


##################
umap <-
  graph_umaps %>%
  filter(dataset_id == "blood") %>% 
  select(-UMAP_1, -UMAP_2) %>%
  left_join(all_clusters_consensus %>% 
              filter(dataset_id == "blood",
                     resolution == 6.7) %>% 
              select(-cons_cluster))

umap %>% 
ggplot(aes(x = UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(size = 0.1, show.legend = F) +
  coord_fixed()+
  theme_void() +
  theme(panel.spacing = unit(0, "mm"))   


############ UMAPS
all_clusterings<- 
  all_clusterings %>% 
  mutate(resolution = as.character(resolution))

blood_clustering <- all_clusterings %>% filter(dataset_id == "blood", resolution == "4.7")
brain_clustering <- all_clusterings %>% filter(dataset_id == "brain", resolution == "6.1")
celline_clustering <- all_clusterings %>% filter(dataset_id == "celline", resolution == "1.7")
tissue_clustering_56 <- all_clusterings %>% filter(dataset_id == "tissue", resolution == "3.5")
tissue_clustering_87 <- all_clusterings %>% filter(dataset_id == "tissue", resolution == "7.3")


graph_umaps %>% 
  filter(dataset_id == "brain") %>% 
  left_join(brain) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Brain - 68 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("brain_68.png")

graph_umaps %>% 
  filter(dataset_id == "blood") %>% 
  left_join(blood) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Blood - 52 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("blood_52.png")

graph_umaps %>% 
  filter(dataset_id == "celline") %>% 
  left_join(celline) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Celline - 44 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("celline_44.png")

graph_umaps %>% 
  filter(dataset_id == "tissue") %>% 
  left_join(tissue_clustering_87) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Tissue - 56 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("tissue_56.png")


graph_umaps %>% 
  filter(dataset_id == "tissue") %>% 
  left_join(tissue_clustering_87) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Tissue - 56 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("tissue_56.png")

graph_umaps %>% 
  filter(dataset_id == "tissue") %>% 
  left_join(tissue_clustering_87) %>% 
  ggplot(aes(x=UMAP_1_scaled, y = UMAP_2_scaled, color = as.factor(cluster))) +
  geom_point(show.legend = F) +
  theme_void() +
  ggtitle("Tissue - 56 clusters") +
  scale_color_manual(values =   colorRampPalette(ggthemes::tableau_color_pal(palette = "Classic Cyclic")(13))(87)) 

ggsave("tissue_56.png")


```



## Summarize evaluation
```{r}
all_clusterings <- 
  all_clusters_consensus %>% 
  select(-cons_cluster) %>% 
  group_by(dataset_id, resolution, cluster) %>% 
  mutate(size = n_distinct(gene)) %>% 
  ungroup() %>% 
  group_by(dataset_id, resolution) %>% 
  mutate(k = n_distinct(cluster),
         min_size = min(size)) %>% 
  ungroup() 

blood <- all_clusterings %>% filter(dataset_id == "blood",
                                          k > 30,
                                          k < 60)
brain <- all_clusterings %>% filter(dataset_id == "brain",
                                          k > 40,
                                          k < 80)
celline <- all_clusterings %>% filter(dataset_id == "celline",
                                          k > 40,
                                          k < 70)
tissue <- all_clusterings %>% filter(dataset_id == "tissue",
                                          k > 70,
                                          k < 100)

singlecell <- all_clusterings %>% filter(dataset_id == "singlecell",
                                          k > 60,
                                          k < 90)



clusterings <- blood %>% 
  full_join(brain) %>% 
  full_join(celline) %>% 
  full_join(tissue)%>% 
  full_join(singlecell)

res_k <- 
  clusterings %>% 
  select(dataset_id, resolution, k, min_size) %>% 
  distinct()

p1 <- 
  clusterings %>% 
  select(dataset_id, resolution, k, min_size) %>% 
  distinct() %>% 
  ggplot(aes(k, min_size, color = dataset_id)) +
  geom_point(size = 1) +
  geom_smooth(show.legend = F) +
  theme_bw() +
  scale_color_manual(values = dataset_palette) +
  scale_fill_manual(values = dataset_palette) +
  facet_grid(~dataset_id, scales = "free_x")+
  theme(
    strip.text.x = element_text(color = "white"),
    strip.text.y = element_text(color = "white"),
    strip.background = element_rect(
      color="grey35", fill="grey52")
  ) +
  ylab("Minimum_cluster_size")

p2 <- 
  intracluster_distances %>% 
  select(dataset_id, resolution, avg_weighted_dist) %>% 
  distinct() %>% 
  left_join(res_k) %>% 
  filter(min_size > 20) %>% 
  ggplot(aes(k, avg_weighted_dist, color = dataset_id)) +
  geom_point(size = 1) +
  geom_smooth(show.legend = F) +
  theme_bw()+
  facet_grid(~dataset_id, scales = "free_x") +
  scale_color_manual(values = dataset_palette) +
  ylab("UMAP_distance")


p3 <- ARI_res %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(avg_ARI = mean(ARI)) %>% 
  left_join(res_k) %>% 
  filter(min_size > 20) %>% 
  ggplot(aes(x = k, y = avg_ARI, color = dataset_id)) +
  geom_point() +
  geom_smooth() +
  facet_grid(~dataset_id, scales = "free_x") +
  theme_bw() +
  scale_color_manual(values = dataset_palette)

p4 <- ARI_res %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(sd_ARI = sd(ARI)) %>% 
  left_join(res_k) %>% 
  filter(min_size > 20) %>% 
  ggplot(aes(x = k, y = sd_ARI, color = dataset_id)) +
  geom_point() +
  geom_smooth() +
  facet_grid(~dataset_id, scales = "free_x") +
  theme_bw() +
  scale_color_manual(values = dataset_palette)

max_ARI <- ARI_res %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(avg_ARI = mean(ARI),
            sd_ARI = sd(ARI)) %>% 
  left_join(res_k) %>% 
  filter(min_size > 20) %>%
  group_by(dataset_id) %>% 
  mutate(avg_ARI_scaled =  scales::rescale(avg_ARI, to = c(0,1)),
         sd_ARI_scaled =  scales::rescale(sd_ARI, to = c(1,0))) %>% 
  select(-sd_ARI,-avg_ARI) %>% 
  gather(measure, value, avg_ARI_scaled,sd_ARI_scaled) %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(avg_ARI = mean(value), k) %>% 
  ungroup() %>% 
  distinct() %>% 
  group_by(dataset_id) %>% 
  top_n(1,wt = avg_ARI) %>%
  mutate(h = case_when(avg_ARI == max(avg_ARI) ~ 1.3,
                       avg_ARI == min(avg_ARI) ~ 1.1))

p5 <- ARI_res %>% 
  group_by(dataset_id, resolution) %>% 
  summarise(avg_ARI = mean(ARI),
            sd_ARI = sd(ARI)) %>% 
  left_join(res_k) %>% 
  filter(min_size > 20) %>%
  group_by(dataset_id) %>% 
  mutate(avg_ARI_scaled =  scales::rescale(avg_ARI, to = c(0,1)),
         sd_ARI_scaled =  scales::rescale(sd_ARI, to = c(1,0))) %>% 
  select(-sd_ARI,-avg_ARI) %>% 
  gather(measure, value, avg_ARI_scaled,sd_ARI_scaled) %>% 
  ggplot(aes(x = k, y = value, group = measure, color = measure)) +
  geom_point() +
  geom_smooth(method = "loess", 
              span = .5) +
  facet_grid(~dataset_id, scales = "free_x") +
  theme_bw() +
   geom_vline(aes(xintercept=k), data = max_ARI, color = "black")+
   geom_label(data =max_ARI,
              aes(x=k,y = h, label = paste(k, "clusters", sep =" "), fill = dataset_id),
              inherit.aes = F,
              size = 3,
              show.legend = F) +
    scale_fill_manual(values = dataset_palette %>% map(~adjust_transparency(.x, alpha = 0.8)) %>% unlist())

  

p1 <- p1 +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
         strip.background = element_rect(
     color="grey35", fill="grey42"),
   
          strip.text = element_text(color = "white"))
p2 <- p2 +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())

p3 <- p3 +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())

p4 <- p4 +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())

p5 <- p5 +
  theme(strip.background = element_blank(),
        strip.text = element_blank()) +
  xlab("Number of clusters (k)")


  
p1 / p2 / p3 / p4 / p5 +
    plot_layout(guides = "collect")
```




# Final clustering
## Manual selection & run seeds
```{r}
# Select final resolution for each dataset & calculate cluster membership matrix
t <- Sys.time()
final_clusterings <- 
  all_clusters_consensus %>% 
  mutate(resolution = as.character(resolution)) %>% 
  inner_join(run_settings$final_consensus_resolutions %>% 
               enframe() %>% 
               mutate(value = as.character(value)) %>% 
               rename(dataset_id =  name,
                      resolution = value)) %>% 
  select(-cons_cluster) %>% 
  group_by(dataset_id) %>% 
  do({
    cluster_res <- .
    g_dataset_id <- 
      unique(cluster_res$dataset_id)
    
    savefile_final_cluster <- 
      paste(file_structure[[g_dataset_id]]$clustering, "final_consensus.tsv", sep = "/")
    savefile_membership <- 
      paste(file_structure[[g_dataset_id]]$clustering, "cluster_memberships.tsv", sep = "/")
    savefile_mapping <- 
      paste(file_structure[[g_dataset_id]]$clustering, "cluster_mapping_final_consensus.tsv", sep = "/")
    
    
    if(file.exists(savefile_final_cluster)) {
      cluster_res <-
        read_tsv(savefile_final_cluster)
      
    } else {
      
      dat <- all_data_cluster %>% 
        filter(dataset_id == g_dataset_id,
               resolution == unique(cluster_res$resolution))
      
      final_clustering <- find_consensus(dat, n = run_settings$num_seeds, get_membership = T, runs = 1)
      
      mapping_table <- 
        final_clustering$consensus_clustering %>% 
        select(cluster, cons_cluster) %>% 
        distinct() %>% 
        arrange(as.numeric(cluster))
      
      cluster_res <- final_clustering$consensus_clustering %>% select(-cons_cluster)
      membership <- final_clustering$membership_matrix %>%  select(-cons_cluster)
      
      write_tsv(cluster_res, savefile_final_cluster)
      write_tsv(membership, savefile_membership)
      write_tsv(mapping_table, savefile_mapping)
      
    }
    cluster_res
    
  }) %>%
  ungroup()
t - Sys.time()


final_clusterings %>% 
  group_by(dataset_id) %>% 
  summarise(n_distinct(cluster))
```


## Generate hulls
```{r}

umap_clusteirng <- 
  graph_umaps %>% 
  select(-UMAP_1,- UMAP_2) %>% 
  left_join(final_clusterings)

# Prepare cluster for parallelizaiton
cluster <- new_cluster(n = 5)
cluster_library(cluster, c("dplyr",
                           "tidyverse",
                           "magrittr",
                           "fpc",
                           "concaveman",
                           "sf")) 
cluster_copy(cluster, c("generate_cluster_hulls", 
                        "file_structure",
                        "get_density"))

# Calculate cluster polygons (based on DBSCAN)
t <- Sys.time()
graph_umaps_hulls <- 
  umap_clusteirng %>% 
  group_by(dataset_id) %>% 
  partition(cluster) %>% 
  do({
    g_data <- .
    
    g_dataset_id <- 
      unique(g_data$dataset_id)
    
    savefile_UMAP_polygons <- 
      paste(file_structure[[g_dataset_id]]$UMAP, "UMAP_polygons.tsv", sep = "/")
    savefile_UMAP_hulls<- 
      paste(file_structure[[g_dataset_id]]$UMAP, "UMAP_hulls.rds", sep = "/")
    
    if(file.exists(savefile_UMAP_hulls)) {
      UMAP_hulls <-
        read_tsv(savefile_UMAP_hulls)
      
    } else {
      
      UMAP_hulls <- 
        g_data %$%
        generate_cluster_hulls(V1 = UMAP_1_scaled,
                       V2 = UMAP_2_scaled, 
                       element_id = gene,
                       cluster_membership = cluster, 
                       n = 1000,
                       poly_concavity = 2,
                       poly_smoothing = 1.25,
                       relative_bandwidth = 1/150)
      
      
      write_tsv(UMAP_hulls$hulls, savefile_UMAP_polygons)
      saveRDS(UMAP_hulls, savefile_UMAP_hulls)
      
      UMAP_hulls$hulls
    }
  }) %>% 
  ungroup() %>% 
  collect()

Sys.time() - t

rm(cluster)


# Visualize cluster polygons
graph_umaps_hulls %>% 
  ggplot(aes(X,Y, group = paste(cluster, sub_cluster, landmass), fill = as.factor(cluster))) +
  geom_polygon(show.legend = F,
               color = "black") +
  theme_bw() +
  facet_grid(~dataset_id) +
  coord_fixed()

ggsave(run_id_savename("UMAP scaled hulls.pdf"),
       width = 8, height = 5)

```

